-- CR-009: Material 子域 - 物料品类（MaterialCategory）主表与历史快照表
-- 同步来源字段采用 Brand/Party 模式（source_system / source_id / source_version / ingestion_channel / ingestion_time / source_payload_hash）

CREATE TABLE IF NOT EXISTS `mdm_material_category` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `code` VARCHAR(64) NOT NULL COMMENT '业务主键，全局唯一',
    `name` VARCHAR(128) NOT NULL COMMENT '品类名称',
    `name_local` VARCHAR(128) DEFAULT NULL COMMENT '本地化名称',
    `description` VARCHAR(512) DEFAULT NULL COMMENT '描述',
    `parent_code` VARCHAR(64) DEFAULT NULL COMMENT '父品类编码（自关联，支持树形结构）',
    `source_system` VARCHAR(32) NOT NULL COMMENT '来源系统编码（LOCAL/PLM/ERP/...）',
    `source_id` VARCHAR(128) DEFAULT NULL COMMENT '上游系统中的业务主键',
    `source_version` VARCHAR(64) DEFAULT NULL COMMENT '上游系统中的版本号',
    `ingestion_channel` VARCHAR(16) NOT NULL COMMENT '接入通道（LOCAL/KAFKA/FEIGN）',
    `ingestion_time` DATETIME NOT NULL COMMENT '最近一次接收/变更时间',
    `source_payload_hash` VARCHAR(64) DEFAULT NULL COMMENT '最近一次接入消息体的哈希值',
    `version` INT NOT NULL DEFAULT 1 COMMENT '业务版本号',
    `effective_from` DATETIME DEFAULT NULL COMMENT '生效开始时间',
    `effective_to` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（DRAFT/ACTIVE/INACTIVE）',
    `create_by` VARCHAR(64) NOT NULL COMMENT '创建人',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `modify_by` VARCHAR(64) NOT NULL COMMENT '修改人',
    `modify_time` DATETIME NOT NULL COMMENT '修改时间',
    `row_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `row_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '行有效标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `UK_MC_CODE` (`code`),
    KEY `IDX_MC_PARENT` (`parent_code`),
    KEY `IDX_MC_STATUS` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料品类表（Material 子域首表）';

CREATE TABLE IF NOT EXISTS `mdm_material_category_history` (
    `snapshot_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '快照主键',
    `entity_id` BIGINT DEFAULT NULL COMMENT '关联主表id（物理删除时为NULL）',
    `operation_type` VARCHAR(16) NOT NULL COMMENT '操作类型（CREATE/UPDATE/DEACTIVATE/DELETE）',
    `snapshot_time` DATETIME NOT NULL COMMENT '快照时间',
    `operator` VARCHAR(64) NOT NULL COMMENT '操作人',
    `code` VARCHAR(64) NOT NULL COMMENT '业务主键',
    `name` VARCHAR(128) NOT NULL COMMENT '品类名称',
    `name_local` VARCHAR(128) DEFAULT NULL COMMENT '本地化名称',
    `description` VARCHAR(512) DEFAULT NULL COMMENT '描述',
    `parent_code` VARCHAR(64) DEFAULT NULL COMMENT '父品类编码',
    `source_system` VARCHAR(32) NOT NULL COMMENT '来源系统编码',
    `source_id` VARCHAR(128) DEFAULT NULL COMMENT '上游系统业务主键',
    `source_version` VARCHAR(64) DEFAULT NULL COMMENT '上游系统版本号',
    `ingestion_channel` VARCHAR(16) NOT NULL COMMENT '接入通道',
    `ingestion_time` DATETIME NOT NULL COMMENT '最近接收/变更时间',
    `source_payload_hash` VARCHAR(64) DEFAULT NULL COMMENT '消息体哈希值',
    `version` INT NOT NULL COMMENT '业务版本号',
    `effective_from` DATETIME DEFAULT NULL COMMENT '生效开始时间',
    `effective_to` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `status` VARCHAR(16) NOT NULL COMMENT '状态',
    `create_by` VARCHAR(64) NOT NULL COMMENT '创建人',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `modify_by` VARCHAR(64) NOT NULL COMMENT '修改人',
    `modify_time` DATETIME NOT NULL COMMENT '修改时间',
    `row_version` INT NOT NULL COMMENT '乐观锁版本号',
    `row_valid` TINYINT(1) NOT NULL COMMENT '行有效标记',
    PRIMARY KEY (`snapshot_id`),
    KEY `IDX_MC_HIST_CODE` (`code`),
    KEY `IDX_MC_HIST_ENTITY` (`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物料品类历史快照表';
