-- CR-009: Material 子域 - 零件（Part）主表与历史快照表
-- 同步来源字段采用 Brand/Party 模式（source_system / source_id / source_version / ingestion_channel / ingestion_time / source_payload_hash）

CREATE TABLE IF NOT EXISTS `mdm_material_part` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `code` VARCHAR(64) NOT NULL COMMENT '业务主键，全局唯一（=零件号）',
    `name` VARCHAR(128) NOT NULL COMMENT '零件名称',
    `name_local` VARCHAR(128) DEFAULT NULL COMMENT '本地化名称',
    `description` VARCHAR(512) DEFAULT NULL COMMENT '描述',
    `category_code` VARCHAR(64) NOT NULL COMMENT '物料品类编码（→ MaterialCategory.code）',
    `part_type` VARCHAR(32) NOT NULL COMMENT '零件类型枚举（RAW_MATERIAL/STANDARD_PART/CUSTOM_PART/SOFTWARE/ASSEMBLY）',
    `vehicle_node_code` VARCHAR(64) DEFAULT NULL COMMENT '车载节点编码（→ EEAD.VehicleNode.code）',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '供应商编码（→ Party.Supplier.code）',
    `is_software` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否软件件',
    `fota_upgradeable` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否可FOTA升级',
    `is_safety_critical` TINYINT(1) DEFAULT NULL COMMENT '是否安全关键件',
    `uom` VARCHAR(32) DEFAULT NULL COMMENT '计量单位',
    `drawing_no` VARCHAR(64) DEFAULT NULL COMMENT '图纸编号',
    `drawing_version` VARCHAR(32) DEFAULT NULL COMMENT '图纸版本',
    `weight` DECIMAL(10,3) DEFAULT NULL COMMENT '重量',
    `weight_uom` VARCHAR(16) DEFAULT NULL COMMENT '重量单位',
    `lifecycle_stage` VARCHAR(32) NOT NULL DEFAULT 'PROTOTYPE' COMMENT '生命周期阶段（PROTOTYPE/PRE_PRODUCTION/MASS_PRODUCTION/PHASE_OUT/OBSOLETE）',
    `substitute_part_code` VARCHAR(64) DEFAULT NULL COMMENT '替代件编码（→ Part.code）',
    `source_system` VARCHAR(32) NOT NULL COMMENT '来源系统编码（LOCAL/PLM/ERP/SRM/...）',
    `source_id` VARCHAR(128) DEFAULT NULL COMMENT '上游系统中的业务主键',
    `source_version` VARCHAR(64) DEFAULT NULL COMMENT '上游系统中的版本号',
    `ingestion_channel` VARCHAR(16) NOT NULL COMMENT '接入通道（LOCAL/KAFKA/FEIGN）',
    `ingestion_time` DATETIME NOT NULL COMMENT '最近一次接收/变更时间',
    `source_payload_hash` VARCHAR(64) DEFAULT NULL COMMENT '最近一次接入消息体的哈希值',
    `version` INT NOT NULL DEFAULT 1 COMMENT '业务版本号',
    `effective_from` DATETIME DEFAULT NULL COMMENT '生效开始时间',
    `effective_to` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（DRAFT/ACTIVE/INACTIVE）',
    `create_by` VARCHAR(64) NOT NULL COMMENT '创建人',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `modify_by` VARCHAR(64) NOT NULL COMMENT '修改人',
    `modify_time` DATETIME NOT NULL COMMENT '修改时间',
    `row_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `row_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '行有效标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `UK_PART_CODE` (`code`),
    KEY `IDX_PART_CATEGORY` (`category_code`),
    KEY `IDX_PART_VEHICLE_NODE` (`vehicle_node_code`),
    KEY `IDX_PART_SUPPLIER` (`supplier_code`),
    KEY `IDX_PART_LIFECYCLE` (`lifecycle_stage`, `status`),
    KEY `IDX_PART_SOURCE` (`source_system`, `source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='零件表（Material 子域第二张主表）';

CREATE TABLE IF NOT EXISTS `mdm_material_part_history` (
    `snapshot_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '快照主键',
    `entity_id` BIGINT DEFAULT NULL COMMENT '关联主表id（物理删除时为NULL）',
    `operation_type` VARCHAR(16) NOT NULL COMMENT '操作类型（CREATE/UPDATE/DEACTIVATE/DELETE）',
    `snapshot_time` DATETIME NOT NULL COMMENT '快照时间',
    `operator` VARCHAR(64) NOT NULL COMMENT '操作人',
    `code` VARCHAR(64) NOT NULL COMMENT '业务主键',
    `name` VARCHAR(128) NOT NULL COMMENT '零件名称',
    `name_local` VARCHAR(128) DEFAULT NULL COMMENT '本地化名称',
    `description` VARCHAR(512) DEFAULT NULL COMMENT '描述',
    `category_code` VARCHAR(64) NOT NULL COMMENT '物料品类编码',
    `part_type` VARCHAR(32) NOT NULL COMMENT '零件类型',
    `vehicle_node_code` VARCHAR(64) DEFAULT NULL COMMENT '车载节点编码',
    `supplier_code` VARCHAR(64) DEFAULT NULL COMMENT '供应商编码',
    `is_software` TINYINT(1) NOT NULL COMMENT '是否软件件',
    `fota_upgradeable` TINYINT(1) NOT NULL COMMENT '是否可FOTA升级',
    `is_safety_critical` TINYINT(1) DEFAULT NULL COMMENT '是否安全关键件',
    `uom` VARCHAR(32) DEFAULT NULL COMMENT '计量单位',
    `drawing_no` VARCHAR(64) DEFAULT NULL COMMENT '图纸编号',
    `drawing_version` VARCHAR(32) DEFAULT NULL COMMENT '图纸版本',
    `weight` DECIMAL(10,3) DEFAULT NULL COMMENT '重量',
    `weight_uom` VARCHAR(16) DEFAULT NULL COMMENT '重量单位',
    `lifecycle_stage` VARCHAR(32) NOT NULL COMMENT '生命周期阶段',
    `substitute_part_code` VARCHAR(64) DEFAULT NULL COMMENT '替代件编码',
    `source_system` VARCHAR(32) NOT NULL COMMENT '来源系统编码',
    `source_id` VARCHAR(128) DEFAULT NULL COMMENT '上游系统业务主键',
    `source_version` VARCHAR(64) DEFAULT NULL COMMENT '上游系统版本号',
    `ingestion_channel` VARCHAR(16) NOT NULL COMMENT '接入通道',
    `ingestion_time` DATETIME NOT NULL COMMENT '最近接收/变更时间',
    `source_payload_hash` VARCHAR(64) DEFAULT NULL COMMENT '消息体哈希值',
    `version` INT NOT NULL COMMENT '业务版本号',
    `effective_from` DATETIME DEFAULT NULL COMMENT '生效开始时间',
    `effective_to` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `status` VARCHAR(16) NOT NULL COMMENT '状态',
    `create_by` VARCHAR(64) NOT NULL COMMENT '创建人',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `modify_by` VARCHAR(64) NOT NULL COMMENT '修改人',
    `modify_time` DATETIME NOT NULL COMMENT '修改时间',
    `row_version` INT NOT NULL COMMENT '乐观锁版本号',
    `row_valid` TINYINT(1) NOT NULL COMMENT '行有效标记',
    PRIMARY KEY (`snapshot_id`),
    KEY `IDX_PART_HIST_CODE` (`code`),
    KEY `IDX_PART_HIST_ENTITY` (`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='零件历史快照表';
