-- V6: CR-006 引入 Party MDM 子域，新增 Supplier（供应商）表

-- ============================================================
-- 1. 供应商主表
-- ============================================================
CREATE TABLE IF NOT EXISTS `mdm_supplier` (
    `id`                     BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
    `code`                   VARCHAR(64)   NOT NULL COMMENT '业务主键，全局唯一',
    `name`                   VARCHAR(128)  NOT NULL COMMENT '供应商正式名称',
    `name_local`             VARCHAR(128)           DEFAULT NULL COMMENT '本地化名称',
    `short_name`             VARCHAR(64)            DEFAULT NULL COMMENT '简称/品牌名',
    `supplier_type`          VARCHAR(32)            DEFAULT NULL COMMENT '业务分类：MATERIAL/COMPONENT/SERVICE/LOGISTICS/OTHER',
    `country`                VARCHAR(64)            DEFAULT NULL COMMENT '所在国家/地区',
    `business_license_no`    VARCHAR(64)            DEFAULT NULL COMMENT '统一社会信用代码/工商注册号',
    `tax_id`                 VARCHAR(64)            DEFAULT NULL COMMENT '税号',
    `registered_address`     VARCHAR(256)           DEFAULT NULL COMMENT '注册地址',
    `contact_name`           VARCHAR(64)            DEFAULT NULL COMMENT '联系人姓名',
    `contact_phone`          VARCHAR(32)            DEFAULT NULL COMMENT '联系人电话',
    `contact_email`          VARCHAR(128)           DEFAULT NULL COMMENT '联系人邮箱',
    `bank_name`              VARCHAR(128)           DEFAULT NULL COMMENT '开户银行',
    `bank_account`           VARCHAR(64)            DEFAULT NULL COMMENT '银行账号',
    `cooperation_start_date` DATE                   DEFAULT NULL COMMENT '合作开始日期',
    `description`            VARCHAR(512)           DEFAULT NULL COMMENT '描述',
    `source_system`          VARCHAR(32)   NOT NULL DEFAULT 'LOCAL' COMMENT '来源系统：LOCAL/ERP/SRM/GROUP_MDM',
    `source_id`              VARCHAR(128)           DEFAULT NULL COMMENT '上游系统中的业务主键',
    `source_version`         VARCHAR(64)            DEFAULT NULL COMMENT '上游系统中的版本号',
    `ingestion_channel`      VARCHAR(16)   NOT NULL DEFAULT 'LOCAL' COMMENT '接入通道：LOCAL/KAFKA/FEIGN',
    `ingestion_time`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近一次接收/变更时间',
    `source_payload_hash`    VARCHAR(64)            DEFAULT NULL COMMENT '最近一次接入消息体的哈希值',
    `version`                INT           NOT NULL DEFAULT 1 COMMENT '业务版本号，每次变更+1',
    `effective_from`         DATETIME               DEFAULT NULL COMMENT '生效开始时间',
    `effective_to`           DATETIME               DEFAULT NULL COMMENT '生效结束时间',
    `status`                 VARCHAR(16)   NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/ACTIVE/INACTIVE',
    `create_by`              VARCHAR(64)   NOT NULL COMMENT '创建人',
    `create_time`            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modify_by`              VARCHAR(64)   NOT NULL COMMENT '修改人',
    `modify_time`            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `row_version`            INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `row_valid`              TINYINT       NOT NULL DEFAULT 1 COMMENT '行有效标记：1-有效，0-无效',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`),
    KEY `idx_source` (`source_system`, `source_id`),
    KEY `idx_supplier_type` (`supplier_type`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商表（Party MDM）';

-- ============================================================
-- 2. 供应商历史快照表
-- ============================================================
CREATE TABLE IF NOT EXISTS `mdm_supplier_history` (
    `snapshot_id`            BIGINT        NOT NULL AUTO_INCREMENT COMMENT '快照主键',
    `entity_id`              BIGINT        NOT NULL COMMENT '关联主表id',
    `code`                   VARCHAR(64)   NOT NULL COMMENT '业务主键',
    `name`                   VARCHAR(128)  NOT NULL COMMENT '供应商正式名称',
    `name_local`             VARCHAR(128)           DEFAULT NULL COMMENT '本地化名称',
    `short_name`             VARCHAR(64)            DEFAULT NULL COMMENT '简称/品牌名',
    `supplier_type`          VARCHAR(32)            DEFAULT NULL COMMENT '业务分类',
    `country`                VARCHAR(64)            DEFAULT NULL COMMENT '所在国家/地区',
    `business_license_no`    VARCHAR(64)            DEFAULT NULL COMMENT '统一社会信用代码/工商注册号',
    `tax_id`                 VARCHAR(64)            DEFAULT NULL COMMENT '税号',
    `registered_address`     VARCHAR(256)           DEFAULT NULL COMMENT '注册地址',
    `contact_name`           VARCHAR(64)            DEFAULT NULL COMMENT '联系人姓名',
    `contact_phone`          VARCHAR(32)            DEFAULT NULL COMMENT '联系人电话',
    `contact_email`          VARCHAR(128)           DEFAULT NULL COMMENT '联系人邮箱',
    `bank_name`              VARCHAR(128)           DEFAULT NULL COMMENT '开户银行',
    `bank_account`           VARCHAR(64)            DEFAULT NULL COMMENT '银行账号',
    `cooperation_start_date` DATE                   DEFAULT NULL COMMENT '合作开始日期',
    `description`            VARCHAR(512)           DEFAULT NULL COMMENT '描述',
    `source_system`          VARCHAR(32)   NOT NULL DEFAULT 'LOCAL' COMMENT '来源系统',
    `source_id`              VARCHAR(128)           DEFAULT NULL COMMENT '上游系统中的业务主键',
    `source_version`         VARCHAR(64)            DEFAULT NULL COMMENT '上游系统中的版本号',
    `ingestion_channel`      VARCHAR(16)   NOT NULL DEFAULT 'LOCAL' COMMENT '接入通道',
    `ingestion_time`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近一次接收/变更时间',
    `source_payload_hash`    VARCHAR(64)            DEFAULT NULL COMMENT '最近一次接入消息体的哈希值',
    `version`                INT           NOT NULL COMMENT '业务版本号',
    `effective_from`         DATETIME               DEFAULT NULL COMMENT '生效开始时间',
    `effective_to`           DATETIME               DEFAULT NULL COMMENT '生效结束时间',
    `status`                 VARCHAR(16)   NOT NULL COMMENT '状态',
    `operation_type`         VARCHAR(16)   NOT NULL COMMENT '操作类型：CREATE/UPDATE/DEACTIVATE/DELETE',
    `snapshot_time`          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '快照时间',
    `operator`               VARCHAR(64)   NOT NULL COMMENT '操作人',
    `create_by`              VARCHAR(64)   NOT NULL COMMENT '创建人',
    `create_time`            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `modify_by`              VARCHAR(64)   NOT NULL COMMENT '修改人',
    `modify_time`            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `row_version`            INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `row_valid`              TINYINT       NOT NULL DEFAULT 1 COMMENT '行有效标记：1-有效，0-无效',
    PRIMARY KEY (`snapshot_id`),
    KEY `idx_entity_id` (`entity_id`),
    KEY `idx_code_version` (`code`, `version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商历史快照表（Party MDM）';
