-- CR-008: Org 子域 - 工厂（Plant）主表与历史快照表
-- 同步来源字段采用 Brand/Party 模式（source_system / source_id / source_version / ingestion_channel / ingestion_time / source_payload_hash）

CREATE TABLE IF NOT EXISTS `mdm_org_plant` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `code` VARCHAR(64) NOT NULL COMMENT '业务主键，全局唯一',
    `name` VARCHAR(128) NOT NULL COMMENT '工厂正式名称',
    `name_en` VARCHAR(128) DEFAULT NULL COMMENT '英文名称',
    `short_name` VARCHAR(64) DEFAULT NULL COMMENT '简称',
    `description` VARCHAR(512) DEFAULT NULL COMMENT '描述',
    `plant_type` VARCHAR(32) NOT NULL COMMENT '工厂类型枚举（VEHICLE_ASSEMBLY/POWERTRAIN/BATTERY/STAMPING/WELDING/PAINTING/OTHER）',
    `legal_entity_code` VARCHAR(64) DEFAULT NULL COMMENT '所属法人编码（本期字符串，不做外键）',
    `cost_center_code` VARCHAR(64) DEFAULT NULL COMMENT '对应成本中心（本期字符串，不做外键）',
    `country` VARCHAR(64) DEFAULT NULL COMMENT '国家',
    `province` VARCHAR(64) DEFAULT NULL COMMENT '省/州',
    `city` VARCHAR(64) DEFAULT NULL COMMENT '城市',
    `address` VARCHAR(256) DEFAULT NULL COMMENT '详细地址',
    `longitude` DECIMAL(10,7) DEFAULT NULL COMMENT '经度',
    `latitude` DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
    `timezone` VARCHAR(64) DEFAULT NULL COMMENT '时区（IANA）',
    `annual_capacity` BIGINT DEFAULT NULL COMMENT '年产能（台/件）',
    `production_lines` INT DEFAULT NULL COMMENT '产线数量',
    `operational_start_date` DATE DEFAULT NULL COMMENT '投产日期',
    `mes_instance` VARCHAR(64) DEFAULT NULL COMMENT '对应MES实例标识',
    `source_system` VARCHAR(32) NOT NULL COMMENT '来源系统编码（LOCAL/ERP/PLM/...）',
    `source_id` VARCHAR(128) DEFAULT NULL COMMENT '上游系统中的业务主键',
    `source_version` VARCHAR(64) DEFAULT NULL COMMENT '上游系统中的版本号',
    `ingestion_channel` VARCHAR(16) NOT NULL COMMENT '接入通道（LOCAL/KAFKA/FEIGN）',
    `ingestion_time` DATETIME NOT NULL COMMENT '最近一次接收/变更时间',
    `source_payload_hash` VARCHAR(64) DEFAULT NULL COMMENT '最近一次接入消息体的哈希值',
    `version` INT NOT NULL DEFAULT 1 COMMENT '业务版本号',
    `effective_from` DATETIME DEFAULT NULL COMMENT '生效开始时间',
    `effective_to` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（DRAFT/ACTIVE/INACTIVE）',
    `create_by` VARCHAR(64) NOT NULL COMMENT '创建人',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `modify_by` VARCHAR(64) NOT NULL COMMENT '修改人',
    `modify_time` DATETIME NOT NULL COMMENT '修改时间',
    `row_version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    `row_valid` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '行有效标记',
    PRIMARY KEY (`id`),
    UNIQUE KEY `UK_PLANT_CODE` (`code`),
    KEY `IDX_PLANT_TYPE_STATUS` (`plant_type`, `status`),
    KEY `IDX_PLANT_COUNTRY_STATUS` (`country`, `status`),
    KEY `IDX_PLANT_SOURCE` (`source_system`, `source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工厂表（Org 子域首表）';

CREATE TABLE IF NOT EXISTS `mdm_org_plant_history` (
    `snapshot_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '快照主键',
    `entity_id` BIGINT DEFAULT NULL COMMENT '关联主表id（物理删除时为NULL）',
    `operation_type` VARCHAR(16) NOT NULL COMMENT '操作类型（CREATE/UPDATE/DEACTIVATE/DELETE）',
    `snapshot_time` DATETIME NOT NULL COMMENT '快照时间',
    `operator` VARCHAR(64) NOT NULL COMMENT '操作人',
    `code` VARCHAR(64) NOT NULL COMMENT '业务主键',
    `name` VARCHAR(128) NOT NULL COMMENT '工厂正式名称',
    `name_en` VARCHAR(128) DEFAULT NULL COMMENT '英文名称',
    `short_name` VARCHAR(64) DEFAULT NULL COMMENT '简称',
    `description` VARCHAR(512) DEFAULT NULL COMMENT '描述',
    `plant_type` VARCHAR(32) NOT NULL COMMENT '工厂类型',
    `legal_entity_code` VARCHAR(64) DEFAULT NULL COMMENT '所属法人编码',
    `cost_center_code` VARCHAR(64) DEFAULT NULL COMMENT '对应成本中心',
    `country` VARCHAR(64) DEFAULT NULL COMMENT '国家',
    `province` VARCHAR(64) DEFAULT NULL COMMENT '省/州',
    `city` VARCHAR(64) DEFAULT NULL COMMENT '城市',
    `address` VARCHAR(256) DEFAULT NULL COMMENT '详细地址',
    `longitude` DECIMAL(10,7) DEFAULT NULL COMMENT '经度',
    `latitude` DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
    `timezone` VARCHAR(64) DEFAULT NULL COMMENT '时区',
    `annual_capacity` BIGINT DEFAULT NULL COMMENT '年产能',
    `production_lines` INT DEFAULT NULL COMMENT '产线数量',
    `operational_start_date` DATE DEFAULT NULL COMMENT '投产日期',
    `mes_instance` VARCHAR(64) DEFAULT NULL COMMENT 'MES实例标识',
    `source_system` VARCHAR(32) NOT NULL COMMENT '来源系统编码',
    `source_id` VARCHAR(128) DEFAULT NULL COMMENT '上游系统业务主键',
    `source_version` VARCHAR(64) DEFAULT NULL COMMENT '上游系统版本号',
    `ingestion_channel` VARCHAR(16) NOT NULL COMMENT '接入通道',
    `ingestion_time` DATETIME NOT NULL COMMENT '最近接收/变更时间',
    `source_payload_hash` VARCHAR(64) DEFAULT NULL COMMENT '消息体哈希值',
    `version` INT NOT NULL COMMENT '业务版本号',
    `effective_from` DATETIME DEFAULT NULL COMMENT '生效开始时间',
    `effective_to` DATETIME DEFAULT NULL COMMENT '生效结束时间',
    `status` VARCHAR(16) NOT NULL COMMENT '状态',
    `create_by` VARCHAR(64) NOT NULL COMMENT '创建人',
    `create_time` DATETIME NOT NULL COMMENT '创建时间',
    `modify_by` VARCHAR(64) NOT NULL COMMENT '修改人',
    `modify_time` DATETIME NOT NULL COMMENT '修改时间',
    `row_version` INT NOT NULL COMMENT '乐观锁版本号',
    `row_valid` TINYINT(1) NOT NULL COMMENT '行有效标记',
    PRIMARY KEY (`snapshot_id`),
    KEY `IDX_PLANT_HIST_CODE` (`code`),
    KEY `IDX_PLANT_HIST_ENTITY` (`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工厂历史快照表';
