mybatis-plus:
  type-aliases-package: net.hwyz.iov.cloud.edd.mdm.service.infrastructure.persistence.po

mdm:
  material:
    software-baseline:
      republish:
        batch-max-size: 500
        batch-commit-size: 100
  eead:
    ta-baseline:
      republish:
        batch-max-size: 500
        batch-commit-size: 100
    swin-definition:
      republish:
        batch-max-size: 500
        batch-commit-size: 100